spring.application.name=swappingeasy
spring.datasource.url=jdbc:mysql://localhost:3306/swapingeasy_db
spring.datasource.username=root
spring.datasource.password=@subham2120

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

server.port=8080



